name: auto_size_text_plus
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 3.0.2
homepage: https://github.com/Oyonde/auto_size_text

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pedantic: '>=1.11.1 <3.0.0'
